crowdsourcing/crowdsourcing/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'crowdsourcing.views.home', name='home'),
    # url(r'^crowdsourcing/', include('crowdsourcing.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    
    #API related
    url(r'api/tasks/$', 'web.views.add_task'),
    url(r'api/answers/$', 'web.views.answers'),
    
    
    #Web interface related
    url(r'^$', 'web.views.tasks'),
    url(r'^tasks/$', 'web.views.tasks'),
    url(r'^tasks/(?P<task_id>\d+)/$', 'web.views.task_detail'),
    
    url(r'^answer_task/(?P<task_id>\d+)/$','web.views.answer_task'),
    #User related
    url(r'^signup/$','web.views.new_user'),
    url(r'^users/$','web.views.users'),
    
    url(r'^login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/login/$','django.contrib.auth.views.login'),
    url(r'^logout/$','web.views.destroy_session'),
    url(r'^accounts/logout/$','web.views.destroy_session'),
    url(r'^accounts/change_password/$','web.views.update_user'),
    url(r'^sessions/$','web.views.sessions'),
)

crowdsourcing/web/models.py
from django.db import models

from django.contrib.auth.models import User

class Companyuser(models.Model):
    user = models.ForeignKey(User,unique=True)

class Task(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    possible_answers = models.TextField(null=True) # JSON-serialized (text) version of your possible answers
    price = models.DecimalField(max_digits=4,decimal_places=2)
    callback = models.URLField()
    answers_wanted = models.IntegerField()
    companyuser = models.ForeignKey(Companyuser)
    
class Answer(models.Model):
    task = models.ForeignKey(Task)
    user = models.ForeignKey(User)
    answer = models.TextField()

crowdsourcing/web/templates/web/detail.html
{% if messages %}
	<div>
    	{% for message in messages %}
        	<h2 class="{{message.tag}}">{{ message.message }}</h2>
        {% endfor %}
    </div>
{% endif %}

<h1>{{task.title}}</h1>
<h2>{{task.content}}</h2>
<p>Price for answering this Task: {{task.price}} €</p>

<p>
{% for answer in possible_answers %}
{{answer}}</br>
{% endfor %}

<form action="/answer_task/{{task.id}}/" method="post">
{% csrf_token %}
<table>
		<tr>
			<td colspan="2" style="text-align:"><h2>Your Answer:</h2></td>
		</tr>
		<tr>
			<td>
				<textarea name="answer"></textarea>
			</td>
		</tr>
		<tr>
			<td colspan="2" style="text-align: right;">
				<br/>
				<input type="submit" value="Submit Answer" style="margin-top: 10px;"/>
			</td>
		</tr>
	</table>
</form>

<a href="/">All Tasks</a>

crowdsourcing/web/templates/web/index.html
<title>AIC13 Crowdsourcing Plattform</title>

<h1>Listing Tasks</h1>
{% if user.is_authenticated %}
  <p>Welcome, {{ user.username }}</a>. Thanks for logging in. <a href="/logout">Logout.</a></p>
  
	{% block content %}
    	{% if messages %}
    	<div>
        	{% for message in messages %}
            	<h2 class="{{message.tag}}">{{ message.message }}</h2>
        	{% endfor %}
    	</div>
    	{% endif %}
	{% endblock %}
	{% if not user.companyuser_set.all %}
	<table>
  		<tr>
    		<th>Title</th>
    		<th>Content</th>
    		<th>Answer</th>
  		</tr>
 
  		{% for task in all_tasks %}
  		<tr>
    		<td>{{task.title}}</td>
    		<td>{{task.content}}</td>
    		<td><a href="/tasks/{{ task.id }}/">Answer</a></td>
  		</tr>
  		{% endfor %}
	</table>
	<br />
	{% else %}
		WebUI for Company Users coming soon
	{% endif %}
{% else %}
	<p>Please <a href="/signup/">signup</a> or <a href="/login/">login</a> to see and answer Tasks.</p>
{% endif %}

crowdsourcing/web/templates/web/signup.html
<form action="/users/" method="post">
	{% csrf_token %}
	<table style="margin-left: auto; margin-right: auto;">
		<tr>
			<td colspan="2" style="text-align: center;"><h1>"Register"</h1></td>
		</tr>
		<tr>
			<th style="text-align: right;">Username:</th>
			<td>
			<input id="username" name="username" type="text" style="width: 200px;"/>
			</td>
		</tr>
		<tr>
			<th style="text-align: right;">"Password":</th>
			<td>
			<input name="password" type="password" style="width: 200px;"/>
			</td>
		</tr>
		<tr>
			<th style="text-align: right;">"Do you want to":</th>
			<td>
				<select name="type">
					<option value="company">Create Tasks</option>
					<option value="worker">Answer Tasks</option>
				</select>
			</td>
		</tr>
		<tr>
			<td colspan="2" style="text-align: right;">
			<br/>
			<input type="submit" value="Register User" style="margin-top: 10px;"/>
			</td>
		</tr>
	</table>
</form>